WidgetPhoto:
  resource: "@WidgetPhotoBundle/Resources/config/routing.yml"

WidgetArticle:
  resource: "@WidgetArticleBundle/Resources/config/routing.yml"

backend_base:
  resource: "@BackendBaseBundle/Resources/config/routing.yml"
