parameters:
    widget_post_photo_config:
        -
            type:           'inbox'
            suffix:         'large'
            width:          1280
            height:         1024
        -
            type:           'inbox'
            suffix:         'medium'
            width:          800
            height:         600
        -
            type:           'inbox'
            suffix:         'small'
            width:          400
            height:         300
services:
#    widget_post.example:
#        class: Widget\PostBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]